name: Build Checklists

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
  
    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"
        enable-cache: true
        cache-dependency-glob: "uv.lock"

    - name: Cache B612 Font
      uses: actions/cache@v4
      id: font-cache
      with:
        path: /usr/share/fonts/b612
        key: b612-font-v1

    - name: Install B612 Font from Google Fonts
      if: steps.font-cache.outputs.cache-hit != 'true'
      run: |
        wget -O B612.zip https://fonts.google.com/download?family=B612
        unzip -d b612/ B612.zip
        sudo mv b612 /usr/share/fonts/
        sudo fc-cache -fv

    - name: Refresh font cache if cached
      if: steps.font-cache.outputs.cache-hit == 'true'
      run: sudo fc-cache -fv

    - name: Install dependencies with uv
      run: uv sync

    - name: Build checklists
      run: make all

    - name: Create or update nightly release
      if: github.event_name == 'workflow_dispatch' || (github.event_name == 'push' && github.ref == 'refs/heads/main')
      uses: softprops/action-gh-release@v2
      with:
        tag_name: nightly
        name: "Latest Build"
        body: |
          Automatically generated checklists from the latest main branch.
          
          Generated on: ${{ github.event.head_commit.timestamp || github.run_id }}
          Commit: ${{ github.sha }}
        prerelease: false
        files: |
          out/*.pdf
        fail_on_unmatched_files: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
