name: Build Checklists

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
  
    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"
        enable-cache: true
        cache-dependency-glob: "uv.lock"

    - name: Cache Fonts
      uses: actions/cache@v4
      id: font-cache
      with:
        path: fonts/
        key: fonts-${{ hashFiles('scripts/download_fonts.py') }}

    - name: Download fonts
      if: steps.font-cache.outputs.cache-hit != 'true'
      run: |
        uv run python scripts/download_fonts.py

    - name: Install dependencies with uv
      run: uv sync

    - name: Build checklists
      run: make all

    - name: Create or update nightly release
      if: github.event_name == 'workflow_dispatch' || (github.event_name == 'push' && github.ref == 'refs/heads/main')
      uses: softprops/action-gh-release@v2
      with:
        tag_name: nightly
        name: "Latest Build"
        body: |
          Automatically generated checklists from the latest main branch.
          
          Generated on: ${{ github.event.head_commit.timestamp || github.run_id }}
          Commit: ${{ github.sha }}
        prerelease: false
        files: |
          out/*.pdf
        fail_on_unmatched_files: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
