name: Build Checklists

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
  
    - name: Install Pandoc & Weasyprint
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc weasyprint

    - uses: fontist/setup-fontist@v2

    - run: fontist install "B612"

    - name: Make fonts available to weasyprint
      run: |
        sudo cp -r ~/.fontist/fonts/* /usr/share/fonts/ || true
        sudo fc-cache -fv

    - name: Build checklists
      run: make all

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: checklists-pdf
        path: out/*.pdf
        retention-days: 30
